#!/bin/bash
top=$(dirname $(dirname $(readlink -f $BASH_SOURCE)))
cd $top

run () {
    $*
    if [ "$?" == "0" ] ; then
	return
    fi
    echo "Failed to run: \"$*\"" 
    echo "Failed to run: \"$*\"" 1>&2
    exit 1
}

build_one () {
    local name=$1 ; shift
    run pdflatex $name
    run bibtex $name
    run pdflatex $name
    run pdflatex $name
}
    
build_all () {
    for maybe in *.tex
    do
	local name="$(basename $maybe .tex)"
	if [ ! -d "$name" ] ; then
	    continue
	fi
	build_one $name
    done
}

clean_all () {
    for maybe in *.tex
    do
	local name="$(basename $maybe .tex)"
	if [ ! -d "$name" ] ; then
	    continue
	fi
	rm ${name}.{aux,bbl,blg,fls,lof,log,lot,toc,nlo,out,pdf,tdo,fdb_latexmk}
    done
}



log="$top/build-all.log"

run_if_updated () {
    date >> $log
    if [ -n "$(git pull|grep 'Already up-to-date.')" ] ; then
	return
    fi

    clean_all >> $log
    build_all >> $log
}

run_if_updated

